### PR TITLE
Fix visualization of And and Not conditionals

### LINKED ISSUE #115: 'And' and 'Not' conditionals not displaying properly
The graphviz code does not properly handle 'And' and 'Not.' Add cases to the renderer so that they are not rendered as 'Unknown Condition.'

### PR DESCRIPTION
**Pull request by kjmahalingam**
Fixes #115.

### CODE REVIEW

File: src/utils/graphviz.js [hunk 1]
```diff
@@ -379,7 +379,7 @@ const stateDescription = (state) =>{
 const logicDetails = logic => {
 
   switch(logic['condition_type']){
-    case 'When':
+    case 'And':
```
Comment (kjmahalingam) [inline src/utils/graphviz.js]: Non-whitespace change.

File: src/utils/graphviz.js [hunk 2]
```diff
@@ -400,7 +400,10 @@ const logicDetails = logic => {
         }
       });
       return `${logic['condition_type']} ${threshold} of:\\l- ${subsOr.join('- ')}`
-    case 'Gender': 
+    case 'Not':
```
Comment (kjmahalingam) [inline src/utils/graphviz.js]: Non-whitespace change.
